# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Main.proto for package 'tell'

require 'grpc'
require 'Main_pb'

module Tell
  module DeviceConfirmation
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tell.DeviceConfirmation'

      rpc :DeviceConfirmation, DeviceInfo, Result
    end

    Stub = Service.rpc_stub_class
  end
end
