# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Main.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tell.DeviceInfo" do
    optional :deviceName, :string, 1
    optional :systemName, :string, 2
    optional :systemVersion, :string, 3
    optional :model, :string, 4
    optional :applicationType, :enum, 5, "tell.ApplicationType"
  end
  add_message "tell.Result" do
    optional :result, :string, 1
  end
  add_enum "tell.ApplicationType" do
    value :NONE, 0
    value :ANDROID, 1
    value :ANDROID_ALPHA, 2
    value :ANDROID_BETA, 3
    value :ANDROID_RC, 4
    value :IOS, 5
    value :IOS_ALPHA, 6
    value :IOS_BETA, 7
    value :IOS_RC, 8
    value :BOT, 9
    value :BOT_ALPHA, 10
    value :BOT_BETA, 11
    value :BOT_RC, 12
    value :WEB, 13
    value :WEB_ALPHA, 14
    value :WEB_BETA, 15
    value :WEB_RC, 16
  end
end

module Tell
  DeviceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("tell.DeviceInfo").msgclass
  Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("tell.Result").msgclass
  ApplicationType = Google::Protobuf::DescriptorPool.generated_pool.lookup("tell.ApplicationType").enummodule
end
